services:
  db:
    image: postgres:16-alpine
    restart: unless-stopped

    environment:
      POSTGRES_DB: eventflow
      POSTGRES_USER: eventflow
      POSTGRES_PASSWORD: eventflow_password

    ports:
      - "5432:5432"

    volumes:
      - eventflow_db:/var/lib/postgresql/data

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U eventflow -d eventflow"]
      interval: 5s
      timeout: 5s
      retries: 10

volumes:
  eventflow_db: