'use client';
import { useEffect,useState } from 'react';
import { CalendarPlus,Users,ClipboardList } from 'lucide-react';
import RoleGuard from '@/components/RoleGuard';
import { Page, Stat, Button } from '@/components/ui';

type Stats={totals:{totalUsers:number;participants:number;conductors:number;admins:number;totalEvents:number;activeEvents:number;completedEvents:number;totalRegistrations:number;totalAttendance:number;pendingRegistrations:number};recentRegistrations:any[]};
export default function Admin(){return <RoleGuard role="admin"><AdminInner/></RoleGuard>}
function AdminInner(){const [data,setData]=useState<Stats|null>(null);useEffect(()=>{fetch('/api/admin/stats',{cache:'no-store'}).then(r=>r.json()).then(setData)},[]);if(!data)return <Page><div>Loading control center...</div></Page>;const t=data.totals;return <Page><div className="flex flex-col md:flex-row md:items-end justify-between gap-4"><div><p className="text-sm text-indigo-300">Administration</p><h1 className="text-4xl font-black">EventFlow Control Center</h1><p className="mt-2 text-slate-400">Manage events, registrations, users and platform access.</p></div><Button href="/admin/events">Create Event <CalendarPlus size={17}/></Button></div><div className="mt-8 grid sm:grid-cols-2 lg:grid-cols-4 gap-4"><Stat label="Total Users" value={t.totalUsers}/><Stat label="Total Events" value={t.totalEvents}/><Stat label="Registrations" value={t.totalRegistrations}/><Stat label="Attendance" value={t.totalAttendance}/></div><div className="mt-8 grid md:grid-cols-3 gap-4"><Stat label="Participants" value={t.participants}/><Stat label="Event Conductors" value={t.conductors}/><Stat label="Pending Registrations" value={t.pendingRegistrations}/></div><section className="mt-10 grid md:grid-cols-3 gap-5"><div className="glass rounded-2xl p-6"><Users className="text-indigo-300"/><h2 className="mt-4 font-bold">User management</h2><p className="mt-2 text-sm text-slate-500">Create and manage platform accounts from the database.</p><Button href="/admin/users" variant="secondary" className="mt-4">Open users</Button></div><div className="glass rounded-2xl p-6"><ClipboardList className="text-indigo-300"/><h2 className="mt-4 font-bold">Registration management</h2><p className="mt-2 text-sm text-slate-500">Review participant registrations and update status.</p><Button href="/admin/registrations" variant="secondary" className="mt-4">Open registrations</Button></div><div className="glass rounded-2xl p-6"><CalendarPlus className="text-indigo-300"/><h2 className="mt-4 font-bold">Event management</h2><p className="mt-2 text-sm text-slate-500">Create, edit, publish or remove events.</p><Button href="/admin/events" variant="secondary" className="mt-4">Manage events</Button></div></section></Page>}
