'use client';
import { useEffect,useState } from 'react';
import RoleGuard from '@/components/RoleGuard';
import {Page,Button,Toast,Badge} from '@/components/ui';
import {api} from '@/lib/client-api';

type User={id:string;name:string;email:string;role:string;status:string};
export default function UsersPage(){return <RoleGuard role="admin"><Inner/></RoleGuard>}
function Inner(){const [users,setUsers]=useState<User[]>([]);const [form,setForm]=useState({name:'',email:'',password:'',role:'EVENT_CONDUCTOR'});const [msg,setMsg]=useState('');const [error,setError]=useState('');const load=()=>fetch('/api/admin/users',{cache:'no-store'}).then(r=>r.json()).then(setUsers);useEffect(()=>{load()},[]);const create=async()=>{setError('');setMsg('');try{await api('/api/admin/users',{method:'POST',body:JSON.stringify(form)});setMsg('Account created.');setForm({name:'',email:'',password:'',role:'EVENT_CONDUCTOR'});load()}catch(e){setError(e instanceof Error?e.message:'Unable to create account')}};return <Page><div><p className="text-sm text-indigo-300">Admin</p><h1 className="text-4xl font-black">User Management</h1><p className="mt-2 text-slate-400">Create platform accounts and view database-backed identities.</p></div>{msg&&<Toast message={msg}/>} {error&&<Toast message={error} type="error"/>}<div className="mt-8 grid lg:grid-cols-[.8fr_1.2fr] gap-6"><div className="glass rounded-2xl p-6"><h2 className="text-xl font-bold">Create account</h2><div className="mt-4 space-y-3"><input placeholder="Name" value={form.name} onChange={e=>setForm({...form,name:e.target.value})} className="w-full rounded-xl border border-white/10 bg-white/5 p-3"/><input placeholder="Email" type="email" value={form.email} onChange={e=>setForm({...form,email:e.target.value})} className="w-full rounded-xl border border-white/10 bg-white/5 p-3"/><input placeholder="Password" type="password" minLength={8} value={form.password} onChange={e=>setForm({...form,password:e.target.value})} className="w-full rounded-xl border border-white/10 bg-white/5 p-3"/><select value={form.role} onChange={e=>setForm({...form,role:e.target.value})} className="w-full rounded-xl border border-white/10 bg-slate-900 p-3"><option value="EVENT_CONDUCTOR">Event Conductor</option><option value="ADMIN">Admin</option><option value="PARTICIPANT">Participant</option></select><Button onClick={create}>Create account</Button></div></div><div className="space-y-3">{users.map(u=><div key={u.id} className="glass rounded-2xl p-5 flex items-center justify-between gap-4"><div><div className="font-bold">{u.name}</div><div className="text-sm text-slate-500">{u.email}</div></div><Badge>{u.role.replace('_',' ')}</Badge></div>)}{!users.length&&<div className="rounded-2xl border border-dashed border-white/10 p-10 text-center text-slate-500">No users have been created yet.</div>}</div></div></Page>}
