'use client';
import { useEffect,useState } from 'react';
import RoleGuard from '@/components/RoleGuard';
import { Page,Button,Toast } from '@/components/ui';
import type { Event } from '@/types';
import { api } from '@/lib/client-api';

const blank={title:'',category:'Technology',startDate:'',endDate:'',venue:'',description:'',capacity:100,registrationDeadline:'',banner:'',registrationFee:0,status:'PUBLISHED'};
export default function ManageEvents(){return <RoleGuard role="admin"><ManageEventsInner/></RoleGuard>}
function ManageEventsInner(){const [list,setList]=useState<Event[]>([]);const [editing,setEditing]=useState<any|null>(null);const [msg,setMsg]=useState('');const [error,setError]=useState('');const load=()=>fetch('/api/events',{cache:'no-store'}).then(r=>r.json()).then(setList);useEffect(()=>{load()},[]);
 const save=async()=>{setError('');try{const payload={...editing,capacity:Number(editing.capacity),registrationFee:Number(editing.registrationFee||0),startDate:new Date(editing.startDate).toISOString(),endDate:new Date(editing.endDate).toISOString(),registrationDeadline:new Date(editing.registrationDeadline).toISOString()};if(editing.id){await api(`/api/events/${editing.id}`,{method:'PATCH',body:JSON.stringify(payload)})}else{await api('/api/events',{method:'POST',body:JSON.stringify(payload)})}setEditing(null);setMsg(editing.id?'Event updated.':'Event created.');load()}catch(e){setError(e instanceof Error?e.message:'Unable to save event')}};
 const remove=async(id:string)=>{if(!confirm('Delete this event?'))return;try{await api(`/api/events/${id}`,{method:'DELETE'});setMsg('Event deleted.');load()}catch(e){setError(e instanceof Error?e.message:'Unable to delete event')}};
 return <Page><div className="flex justify-between items-center"><div><p className="text-sm text-indigo-300">Admin</p><h1 className="text-4xl font-black">Event Management</h1></div><Button onClick={()=>setEditing({...blank})}>Create Event</Button></div>{msg&&<Toast message={msg}/>} {error&&<Toast message={error} type="error"/>}<div className="mt-8 space-y-3">{list.map(e=><div key={e.id} className="glass rounded-2xl p-5 flex flex-col md:flex-row md:items-center justify-between gap-3"><div><h3 className="font-bold">{e.title}</h3><p className="text-sm text-slate-500">{e.category} · {new Date(e.date).toLocaleDateString('en-IN')} · {e.registered}/{e.seats}</p></div><div className="flex gap-2"><Button variant="secondary" onClick={()=>setEditing({id:e.id,title:e.title,category:e.category,startDate:e.date.slice(0,16),endDate:e.date.slice(0,16),venue:e.location,description:e.description,capacity:e.seats,registrationDeadline:e.deadline.slice(0,16),banner:e.image,registrationFee:e.registrationFee||0,status:e.status||'PUBLISHED'})}>Edit</Button><Button variant="danger" onClick={()=>remove(e.id)}>Delete</Button></div></div>)}{!list.length&&<div className="rounded-2xl border border-dashed border-white/10 p-10 text-center text-slate-500">No published events yet.</div>}</div>{editing&&<div className="fixed inset-0 z-50 bg-black/70 p-4 grid place-items-center"><div className="glass rounded-2xl p-6 w-full max-w-3xl max-h-[90vh] overflow-y-auto"><h2 className="text-2xl font-bold">{editing.id?'Edit Event':'Create Event'}</h2><div className="mt-5 grid md:grid-cols-2 gap-4">{[['title','Title'],['category','Category'],['startDate','Start date'],['endDate','End date'],['venue','Venue'],['capacity','Capacity'],['registrationDeadline','Registration deadline'],['banner','Banner URL'],['registrationFee','Registration fee']].map(([k,l])=><label key={k} className="text-sm text-slate-300">{l}<input type={k==='capacity'||k==='registrationFee'?'number':k.includes('Date')?'datetime-local':'text'} value={editing[k]??''} onChange={e=>setEditing({...editing,[k]:e.target.value})} className="mt-2 w-full rounded-xl border border-white/10 bg-white/5 p-3"/></label>)}<label className="text-sm text-slate-300 md:col-span-2">Description<textarea value={editing.description||''} onChange={e=>setEditing({...editing,description:e.target.value})} className="mt-2 w-full rounded-xl border border-white/10 bg-white/5 p-3" rows={5}/></label></div><div className="mt-5 flex justify-end gap-2"><Button variant="secondary" onClick={()=>setEditing(null)}>Cancel</Button><Button onClick={save}>Save Event</Button></div></div></div>}</Page>}
