'use client';
import { FormEvent, useState } from 'react';
import { useRouter } from 'next/navigation';
import { Page, Button } from '@/components/ui';
import { api } from '@/lib/client-api';

const initialForm={name:'',email:'',password:'',confirmPassword:'',phone:'',college:'',department:'',year:''};
export default function RegisterAccount(){
  const router=useRouter(); const [form,setForm]=useState(initialForm); const [error,setError]=useState(''); const [loading,setLoading]=useState(false);
  const update=(k:keyof typeof initialForm,v:string)=>setForm(x=>({...x,[k]:v}));
  async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();setError('');if(form.password.length<8)return setError('Password must contain at least 8 characters.');if(form.password!==form.confirmPassword)return setError('Passwords do not match.');if(!/^[6-9]\d{9}$/.test(form.phone))return setError('Enter a valid 10-digit Indian mobile number.');setLoading(true);try{await api('/api/auth/register',{method:'POST',body:JSON.stringify({name:form.name,email:form.email,password:form.password,phone:form.phone,college:form.college,department:form.department,year:form.year})});router.replace(`/login?registered=1&email=${encodeURIComponent(form.email.trim().toLowerCase())}`)}catch(err){setError(err instanceof Error?err.message:'Unable to create the account.');setLoading(false)}}
  return <Page><div className="mx-auto max-w-3xl py-6 md:py-10"><div className="text-center"><div className="text-sm text-indigo-300">Participant account</div><h1 className="mt-2 text-4xl font-black md:text-5xl">Create your EventFlow account</h1><p className="mt-3 text-slate-400">Create an account, then sign in before registering for events.</p></div><form onSubmit={submit} className="glass mt-8 grid gap-5 rounded-3xl p-6 md:grid-cols-2 md:p-8">{[['name','Full Name','text'],['email','Email','email'],['password','Password','password'],['confirmPassword','Confirm Password','password'],['phone','Phone Number','tel'],['college','College / Organization','text'],['department','Department','text']].map(([k,l,t])=><Field key={k} label={l} type={t} value={form[k as keyof typeof initialForm]} onChange={v=>update(k as keyof typeof initialForm,v)} />)}<div><label className="text-sm text-slate-300">Year</label><select data-testid="register-year" value={form.year} onChange={e=>update('year',e.target.value)} required className="mt-2 w-full rounded-xl border border-white/10 bg-slate-900 p-3"><option value="">Select year</option><option>1st Year</option><option>2nd Year</option><option>3rd Year</option><option>4th Year</option></select></div>{error&&<div className="md:col-span-2 rounded-xl border border-red-400/20 bg-red-400/10 p-3 text-sm text-red-200">{error}</div>}<div className="md:col-span-2 flex justify-between gap-3"><Button href="/login" variant="secondary">Back to Login</Button><span data-testid="register-submit"><Button type="submit" disabled={loading}>{loading?'Creating...':'Create Account'}</Button></span></div></form></div></Page>
}
function Field({label,type,value,onChange}:{label:string;type:string;value:string;onChange:(v:string)=>void}){return <label className="text-sm text-slate-300">{label}<input data-testid={label==='Full Name'?'register-name':label==='Email'?'register-email':label==='Password'?'register-password':label==='Confirm Password'?'register-confirm-password':label==='Phone Number'?'register-phone':label==='College / Organization'?'register-college':'register-department'} type={type} value={value} onChange={e=>onChange(e.target.value)} required minLength={label==='Password'||label==='Confirm Password'?8:2} className="mt-2 w-full rounded-xl border border-white/10 bg-white/5 p-3 outline-none focus:border-indigo-400/50"/></label>}
