- name: Install Docker
  apt:
    name: [docker.io, docker-compose-plugin]
    state: present
    update_cache: true
- name: Enable Docker
  service:
    name: docker
    state: started
    enabled: true
