import { CheckCircle2, GitBranch, TestTube2, ShieldCheck, Container, ServerCog, PlayCircle, Clock3 } from 'lucide-react';
import { prisma } from '@/lib/prisma';
import { Page, Badge } from '@/components/ui';
import { pipeline as pendingPipeline } from '@/lib/data';

export const dynamic = 'force-dynamic';

export default async function Devops(){
  const run = await prisma.pipelineRun.findFirst({ orderBy: { startedAt: 'desc' }, include: { stages: { orderBy: { startedAt: 'asc' } } } });
  const live = run?.stages?.length ? run.stages.map((s) => ({ name: s.name, tool: s.name.includes('Selenium') ? 'Selenium' : s.name.includes('Build') ? 'Jenkins' : s.name.includes('Docker') ? 'Docker' : s.name.includes('Deployment') ? 'Ansible' : s.name.includes('Security') ? 'DevSecOps' : 'CI', status: s.status.toLowerCase(), description: `Build #${run.buildNumber}` })) : pendingPipeline;
  return <Page><div><p className="text-sm text-indigo-300">Admin / Engineering</p><h1 className="text-4xl font-black">DevSecOps Pipeline</h1><p className="mt-3 max-w-3xl text-slate-400">This page is Admin-only. Pipeline records are stored in PostgreSQL and can be populated by Jenkins executions.</p></div><div className="mt-6 glass rounded-2xl p-5 flex flex-wrap gap-6 text-sm text-slate-400"><span>Latest build: {run?`#${run.buildNumber}`:'No builds yet'}</span><span>Branch: {run?.branch||'—'}</span><span>Commit: {run?.commitHash||'—'}</span><span className="inline-flex items-center gap-2"><Clock3 size={15}/> {run?.completedAt?new Date(run.completedAt).toLocaleString('en-IN'):'Awaiting Jenkins'}</span></div><div className="mt-10 grid lg:grid-cols-7 gap-3">{live.map((p:any,i:number)=><div key={p.name} className="glass rounded-2xl p-4 relative"><div className="flex justify-between">{String(p.status).toLowerCase()==='success'?<CheckCircle2 className="text-emerald-400" size={20}/>:<span className="h-5 w-5 rounded-full border border-slate-500/40"/>}<Badge status={String(p.status).toLowerCase()}/></div><div className="mt-4 text-sm font-bold">{p.name}</div><div className="mt-1 text-xs text-indigo-300">{p.tool}</div><p className="mt-2 text-xs text-slate-500">{p.description}</p>{i<live.length-1&&<div className="hidden lg:block absolute top-8 -right-4 w-5 border-t border-indigo-400/40"/>}</div>)}</div><section className="mt-12 grid md:grid-cols-2 lg:grid-cols-3 gap-5">{[[GitBranch,'Git / GitHub','Version control and auditable source history.'],[PlayCircle,'Jenkins','CI/CD orchestration and build gates.'],[TestTube2,'Selenium','Browser-level automated validation.'],[ShieldCheck,'DevSecOps','Security checks integrated into delivery.'],[Container,'Docker','Repeatable application packaging.'],[ServerCog,'Ansible','Configuration and deployment automation.']].map(([I,t,d]:any)=><div className="glass rounded-2xl p-6" key={t}><I className="text-indigo-300"/><h3 className="mt-4 font-bold">{t}</h3><p className="mt-2 text-sm text-slate-400">{d}</p></div>)}</section></Page>
}
